# Generated by Logic Gate Architect Compiler
# Circuit: FullAdder

def simulate(A, B, Cin):
    xor1 = A ^ B
    Sum = xor1 ^ Cin
    and1 = A & B
    and2 = xor1 & Cin
    Cout = and1 | and2
    return Sum, Cout

# Truth Table
print("A  B  Cin || Sum  Cout")
print("-" * 40)

result = simulate(0, 0, 0)
print(f"0  0  0 || {result[0]}  {result[1]}".format(result=result))
result = simulate(0, 0, 1)
print(f"0  0  1 || {result[0]}  {result[1]}".format(result=result))
result = simulate(0, 1, 0)
print(f"0  1  0 || {result[0]}  {result[1]}".format(result=result))
result = simulate(0, 1, 1)
print(f"0  1  1 || {result[0]}  {result[1]}".format(result=result))
result = simulate(1, 0, 0)
print(f"1  0  0 || {result[0]}  {result[1]}".format(result=result))
result = simulate(1, 0, 1)
print(f"1  0  1 || {result[0]}  {result[1]}".format(result=result))
result = simulate(1, 1, 0)
print(f"1  1  0 || {result[0]}  {result[1]}".format(result=result))
result = simulate(1, 1, 1)
print(f"1  1  1 || {result[0]}  {result[1]}".format(result=result))
