# Generated by Logic Gate Architect Compiler
# Circuit: HalfAdder

def simulate(A, B):
    Sum = A ^ B
    Carry = A & B
    return Sum, Carry

# Truth Table
print("A  B || Sum  Carry")
print("-" * 40)

result = simulate(0, 0)
print(f"0  0 || {result[0]}  {result[1]}")
result = simulate(0, 1)
print(f"0  1 || {result[0]}  {result[1]}")
result = simulate(1, 0)
print(f"1  0 || {result[0]}  {result[1]}")
result = simulate(1, 1)
print(f"1  1 || {result[0]}  {result[1]}")
